In [ ]:
import numpy as np
x = np.array([1, 2, 3])
h = np.array([0.5, 1, 0.5])
y = np.convolve(x, h)
print(y)

[0.5 2.  4.  4.  1.5]


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4])
h = np.array([1, 1, 1])
N = len(x) + len(h) - 1
X = np.fft.fft(x, n=N)
H = np.fft.fft(h, n=N)
Y = X * H
y = np.fft.ifft(Y).real
print(y)

[1. 3. 6. 9. 7. 4.]


In [5]:
import numpy as np
from scipy.signal import correlate
x = np.array([1, 2, 3, 4, 5])
y = np.array([0, 1, 0, -1, 0])
corr_xy = correlate(x, y, mode='full')
print(corr_xy)

[ 0 -1 -2 -2 -2 -2  4  5  0]


# **Auto-correlation**
Auto-correlation is a mathematical operation that measures the similarity between a signal and a delayed version of itself. It is often used in signal processing to find patterns in a signal, detect periodicity, and estimate pitch.

In [4]:
import numpy as np

def auto_correlation(x):
    # Compute the auto-correlation of the signal
    return np.correlate(x, x, mode='same')

# Example usage
x = np.array([1, 2, 3, 4, 5])
r = auto_correlation(x)
print(r)

[26 40 55 40 26]
